const seed={
 commissionPercent:10,
 installationDeals:[
 {id:'INST-1',date:'2026-09-02',requester:'Nile Facilities Co.',requesterName:'Ahmed Hassan',building:'Al Noor Tower',area:'Nasr City',address:'Abbas El Akkad St., Nasr City',floors:18,elevatorType:'Gearless',capacity:'1000 kg / 13 persons',notes:'New tower, two elevators planned. Machine room already built.',status:'In progress',winner:'Marina Property Group',price:850000,days:60,commissionPercent:10,commissionPaid:false,adminNote:'',offers:[{company:'Marina Property Group',price:850000,days:60,note:'Includes 2 years warranty.'},{company:'Nile Facilities Co.',price:910000,days:45,note:''}]},
 {id:'INST-2',date:'2026-09-15',requester:'Marina Property Group',requesterName:'Mona Ali',building:'Cairo Plaza',area:'Maadi',address:'Road 9, Maadi',floors:22,elevatorType:'MRL',capacity:'630 kg / 8 persons',notes:'Replacement of an old geared elevator.',status:'Open',winner:'',price:0,days:0,commissionPercent:0,commissionPaid:false,adminNote:'',offers:[{company:'Nile Facilities Co.',price:620000,days:40,note:'Can start next week.'}]}
 ],
 companies:[{id:'co-1',name:'Nile Facilities Co.',createdAt:'2024-01-10',active:true,plan:'Pro',maxElevators:50,maxTechnicians:20,renewalDate:'2027-01-10'},{id:'co-2',name:'Marina Property Group',createdAt:'2024-03-02',active:true,plan:'Basic',maxElevators:10,maxTechnicians:5,renewalDate:'2027-03-02'}],
 platformUsers:[{id:'u-1',companyId:'co-1',name:'Ahmed Hassan',email:'ahmed@elevator.com',role:'Owner',active:true},{id:'u-2',companyId:'co-1',name:'Mohamed Adel',email:'mohamed@elevator.com',role:'Technician',active:true},{id:'u-3',companyId:'co-2',name:'Mona Ali',email:'mona@elevator.com',role:'Owner',active:true}],
 owners:[{id:1,companyId:'co-1',name:'Ahmed Hassan',email:'ahmed@elevator.com',phone:'01012345678',buildings:4,status:'Active',elevators:8},{id:2,companyId:'co-2',name:'Mona Ali',email:'mona@elevator.com',phone:'01122334455',buildings:3,status:'Active',elevators:5}],
 technicians:[{id:1,companyId:'co-1',name:'Mohamed Adel',email:'mohamed@elevator.com',phone:'01099887766',zone:'Nasr City',status:'Available'},{id:2,companyId:'co-2',name:'Omar Samy',email:'omar@elevator.com',phone:'01288776655',zone:'Maadi',status:'Busy'},{id:3,companyId:'co-1',name:'Karim Tarek',email:'karim@elevator.com',phone:'01177665544',zone:'New Cairo',status:'Available'},{id:4,companyId:'co-2',name:'Youssef Nabil',email:'youssef@elevator.com',phone:'01066554433',zone:'Heliopolis',status:'Available'}], technicianApplications:[{id:'TA-1001',companyId:'co-1',name:'Mostafa Hassan',email:'mostafa.hassan@email.com',phone:'01055551234',zone:'Nasr City',address:'Nasr City, Cairo',experience:'Elevator maintenance technician',yearsExperience:5,specializations:'Electrical systems, door systems, preventive maintenance',appliedDate:'2026-09-10',status:'Pending',notes:'Available for emergency and scheduled service.'},{id:'TA-1002',companyId:'co-2',name:'Ahmed Gamal',email:'ahmed.gamal@email.com',phone:'01144457890',zone:'Maadi',address:'Maadi, Cairo',experience:'Field service technician',yearsExperience:3,specializations:'Hydraulic elevators, troubleshooting, inspections',appliedDate:'2026-09-09',status:'Pending',notes:'Has experience with residential and commercial buildings.'},{id:'TA-1003',companyId:'co-1',name:'Khaled Mostafa',email:'khaled.m@email.com',phone:'01233346781',zone:'New Cairo',address:'New Cairo, Cairo',experience:'Elevator service engineer',yearsExperience:7,specializations:'Gearless machines, MRL, control panels',appliedDate:'2026-09-07',status:'Pending',notes:'Can cover New Cairo and nearby service areas.'}],
 elevators:[{id:1,ownerId:1,building:'Al Noor Tower',elevatorNo:'L-02',floorNo:18,machineType:'Gearless',doorType:'Automatic Center Opening',capacity:'1000 kg / 13 persons',speed:'1.75 m/s',installationYear:2021,status:'Operational'},{id:2,ownerId:1,building:'Al Noor Tower',elevatorNo:'L-03',floorNo:18,machineType:'Geared',doorType:'Automatic Telescopic',capacity:'800 kg / 10 persons',speed:'1.50 m/s',installationYear:2020,status:'Maintenance'},{id:3,ownerId:2,building:'Cairo Plaza',elevatorNo:'L-11',floorNo:22,machineType:'Gearless',doorType:'Automatic Center Opening',capacity:'1000 kg / 13 persons',speed:'1.75 m/s',installationYear:2022,status:'Operational'}],
 requests:[{id:'#REQ-1048',building:'Al Noor Tower',elevator:'L-02',zone:'Nasr City',issue:'Door sensor failure',priority:'Emergency',status:'In progress',technician:'Mohamed Adel',time:'8 min ago'},{id:'#REQ-1047',building:'Cairo Plaza',elevator:'L-11',zone:'Maadi',issue:'Unusual vibration',priority:'High',status:'Open',technician:'Unassigned',time:'24 min ago'},{id:'#REQ-1046',building:'Nile Residence',elevator:'L-03',zone:'New Cairo',issue:'Button panel issue',priority:'Normal',status:'Completed',technician:'Karim Tarek',time:'1 hr ago'},{id:'#REQ-1045',building:'Garden Heights',elevator:'L-07',zone:'Heliopolis',issue:'Lighting problem',priority:'High',status:'In progress',technician:'Youssef Nabil',time:'2 hrs ago'}]
};
function db(){if(!localStorage.getItem('elevator-admin-db'))localStorage.setItem('elevator-admin-db',JSON.stringify(seed));const x=JSON.parse(localStorage.getItem('elevator-admin-db'));x.requests=x.requests||[];x.owners=x.owners||[];x.elevators=x.elevators||[];x.technicians=x.technicians||[];x.technicianApplications=x.technicianApplications||[];x.companies=x.companies||seed.companies;if(x.commissionPercent==null)x.commissionPercent=10;if(!x.installationDeals||x.installationDeals.some(d=>!d.offers))x.installationDeals=seed.installationDeals;const dc=(x.companies[0]||{}).id;[x.owners,x.technicians,x.technicianApplications].forEach(l=>l.forEach(i=>{i.companyId=i.companyId||dc}));x.platformUsers=x.platformUsers||seed.platformUsers;x.requests.forEach(r=>{const o=x.owners.find(o=>o.id===r.ownerId)||x.owners.find(o=>o.name===r.ownerName)||x.owners[0];if(o){r.ownerId=r.ownerId||o.id;r.ownerName=r.ownerName||o.name;r.ownerPhone=r.ownerPhone||o.phone}r.problemDate=r.problemDate||r.date||'2026-09-10';r.date=r.date||r.problemDate});saveDB(x);return x}
function saveDB(x){localStorage.setItem('elevator-admin-db',JSON.stringify(x))}
function techniciansForZone(zone,companyId){return db().technicians.filter(t=>t.zone===zone && t.status!=='Inactive' && (!companyId||t.companyId===companyId))}
function companyName(id){const c=db().companies.find(c=>c.id===id);return c?c.name:'Unassigned'}
function companyOptions(sel){return db().companies.map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}${c.active?'':' (suspended)'}</option>`).join('')}
function reqCompanyId(x,r){const o=x.owners.find(o=>o.id===r.ownerId);return o?o.companyId:''}
function companyFilterVal(){return document.getElementById('companyFilter')?.value||''}
function initCompanyFilter(){const f=document.getElementById('companyFilter');if(f&&!f.options.length)f.innerHTML='<option value="">All companies</option>'+companyOptions()}
function syncPlatformUser(x,item,role){const email=item.email.trim().toLowerCase();const u=x.platformUsers.find(u=>u.email===email);if(u){u.companyId=item.companyId;u.name=item.name}else x.platformUsers.push({id:'u-'+Date.now()+Math.floor(Math.random()*1000),companyId:item.companyId,name:item.name,email,role,active:true})}
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openModal(title,body){let m=document.getElementById('adminModal');if(!m){m=document.createElement('div');m.id='adminModal';m.className='modal';document.body.appendChild(m)}m.innerHTML=`<div class="modal-backdrop" onclick="closeModal()"></div><div class="modal-card"><div class="modal-head"><div><h2>${title}</h2><p>Admin control</p></div><button onclick="closeModal()">×</button></div>${body}</div>`;requestAnimationFrame(()=>m.classList.add('show'))}
function closeModal(){const m=document.getElementById('adminModal');if(m){m.classList.remove('show');setTimeout(()=>m.remove(),180)}}
function addOwner(){openModal('Add owner + elevator',`<form onsubmit="submitOwner(event)"><div class="step-title">1. Owner details</div><div class="form-grid"><label>Company<select id="ownerCompany" required>${companyOptions()}</select></label><label>Full name<input id="ownerName" required placeholder="Owner name"></label><label>Email<input id="ownerEmail" type="email" required placeholder="owner@email.com"></label><label>Phone<input id="ownerPhone" required placeholder="01xxxxxxxxx"></label><label>Status<select id="ownerStatus"><option>Active</option><option>Inactive</option></select></label></div><div class="step-title">2. First elevator details</div><div class="form-grid"><label>Building name<input id="elBuilding" required placeholder="Al Noor Tower"></label><label>Elevator No.<input id="elNo" required placeholder="L-01"></label><label>Floor No.<input id="elFloor" type="number" min="1" required placeholder="18"></label><label>Machine type<select id="elMachine"><option>Gearless</option><option>Geared</option><option>Hydraulic</option><option>MRL</option></select></label><label>Door type<select id="elDoor"><option>Automatic Center Opening</option><option>Automatic Telescopic</option><option>Manual</option><option>Automatic Side Opening</option></select></label><label>Capacity<input id="elCapacity" placeholder="1000 kg / 13 persons"></label><label>Speed<input id="elSpeed" placeholder="1.75 m/s"></label><label>Installation year<input id="elYear" type="number" min="1980" max="2100" placeholder="2026"></label><label>Elevator status<select id="elStatus"><option>Operational</option><option>Maintenance</option><option>Out of Service</option></select></label></div><p class="hint">You can add the owner now with the first elevator. More elevators can be added later from the owner details.</p><button class="gold-btn" type="submit">Create owner & elevator</button></form>`)}
function submitOwner(e){e.preventDefault();const x=db(),ownerId=Date.now(),elevatorId=ownerId+1;const owner={id:ownerId,companyId:ownerCompany.value,name:ownerName.value,email:ownerEmail.value,phone:ownerPhone.value,buildings:1,status:ownerStatus.value,elevators:1};x.owners.push(owner);syncPlatformUser(x,owner,'Owner');x.elevators=x.elevators||[];x.elevators.push({id:elevatorId,ownerId,building:elBuilding.value,elevatorNo:elNo.value,floorNo:Number(elFloor.value),machineType:elMachine.value,doorType:elDoor.value,capacity:elCapacity.value||'Not specified',speed:elSpeed.value||'Not specified',installationYear:Number(elYear.value)||new Date().getFullYear(),status:elStatus.value});saveDB(x);closeModal();renderOwners()}
function addElevator(ownerId){const o=db().owners.find(a=>a.id===ownerId);if(!o)return;openModal(`Add elevator for ${esc(o.name)}`,`<form onsubmit="submitElevator(event,${ownerId})"><div class="form-grid"><label>Building name<input id="elBuilding" required placeholder="Building name"></label><label>Elevator No.<input id="elNo" required placeholder="L-01"></label><label>Floor No.<input id="elFloor" type="number" min="1" required placeholder="18"></label><label>Machine type<select id="elMachine"><option>Gearless</option><option>Geared</option><option>Hydraulic</option><option>MRL</option></select></label><label>Door type<select id="elDoor"><option>Automatic Center Opening</option><option>Automatic Telescopic</option><option>Manual</option><option>Automatic Side Opening</option></select></label><label>Capacity<input id="elCapacity" placeholder="1000 kg / 13 persons"></label><label>Speed<input id="elSpeed" placeholder="1.75 m/s"></label><label>Installation year<input id="elYear" type="number" min="1980" max="2100" placeholder="2026"></label><label>Elevator status<select id="elStatus"><option>Operational</option><option>Maintenance</option><option>Out of Service</option></select></label></div><button class="gold-btn" type="submit">Add elevator</button></form>`)}
function submitElevator(e,ownerId){e.preventDefault();const x=db();x.elevators=x.elevators||[];x.elevators.push({id:Date.now(),ownerId,building:elBuilding.value,elevatorNo:elNo.value,floorNo:Number(elFloor.value),machineType:elMachine.value,doorType:elDoor.value,capacity:elCapacity.value||'Not specified',speed:elSpeed.value||'Not specified',installationYear:Number(elYear.value)||new Date().getFullYear(),status:elStatus.value});const o=x.owners.find(a=>a.id===ownerId);o.elevators=(o.elevators||0)+1;o.buildings=Math.max(o.buildings||0,1);saveDB(x);closeModal();renderOwners()}
function addTechnician(){openModal('Add technician',`<form onsubmit="submitTech(event)"><div class="form-grid"><label>Company<select id="techCompany" required>${companyOptions()}</select></label><label>Full name<input id="techName" required placeholder="Technician name"></label><label>Email<input id="techEmail" type="email" required placeholder="tech@email.com"></label><label>Phone<input id="techPhone" required placeholder="01xxxxxxxxx"></label><label>Zone<select id="techZone">${['Nasr City','Maadi','New Cairo','Heliopolis'].map(z=>`<option>${z}</option>`).join('')}</select></label><label>Status<select id="techStatus"><option>Available</option><option>Busy</option><option>Inactive</option></select></label></div><button class="gold-btn" type="submit">Add technician</button></form>`)}
function submitTech(e){e.preventDefault();const x=db();const nt={id:Date.now(),companyId:techCompany.value,name:techName.value,email:techEmail.value,phone:techPhone.value,zone:techZone.value,status:techStatus.value};x.technicians.push(nt);syncPlatformUser(x,nt,'Technician');saveDB(x);closeModal();renderTechnicians()}
function assignRequest(id){const x=db(),r=x.requests.find(a=>a.id===id);if(!r)return;const own=x.owners.find(o=>o.id===r.ownerId),techs=techniciansForZone(r.zone,own&&own.companyId);openModal(`Assign ${esc(r.id)}`,`<div class="assign-box"><div class="assign-request"><b>${esc(r.issue)}</b><span>Problem date: <b>${esc(r.problemDate||r.date||'Not set')}</b></span><span>Owner: <b>${esc(r.ownerName||'Unknown owner')}</b> · Phone: <b>${esc(r.ownerPhone||'Not provided')}</b></span><span>Building: <b>${esc(r.building)}</b> · Elevator: <b>${esc(r.elevator)}</b> · Zone: <b>${esc(r.zone)}</b></span><span>Priority: <b>${esc(r.priority)}</b> · Current status: <b>${esc(r.status)}</b></span></div>${techs.length?`<label>Technician<select id="assignTech">${techs.map(t=>`<option value="${esc(t.name)}" ${t.name===r.technician?'selected':''}>${esc(t.name)} — ${esc(t.status)}</option>`).join('')}</select></label><p class="hint">Only technicians of <b>${esc(companyName(own&&own.companyId))}</b> registered in <b>${esc(r.zone)}</b> are available.</p><button class="gold-btn" onclick="saveAssignment('${id}')">Assign technician</button>`:`<div class="empty-inline">No active technicians are registered for <b>${esc(r.zone)}</b>.</div>`}</div>`)}
function saveAssignment(id){const x=db(),r=x.requests.find(a=>a.id===id);r.technician=document.getElementById('assignTech').value;r.status='Assigned';saveDB(x);closeModal();renderRequests()}
function renderOwners(){const el=document.getElementById('owners');if(!el)return;const x=db();const esc2=esc;initCompanyFilter();el.innerHTML=x.owners.filter(o=>!companyFilterVal()||o.companyId===companyFilterVal()).map(o=>{const els=(x.elevators||[]).filter(e=>e.ownerId===o.id);return `<tr><td><div class="person"><div class="avatar">${initials(o.name)}</div><div><b>${esc2(o.name)}</b><small>${esc2(o.email)}</small></div></div></td><td><span class="badge gold">${esc2(companyName(o.companyId))}</span></td><td>${esc2(o.phone)}<small>${o.buildings||0} building(s)</small></td><td><div class="detail-stack">${els.length?els.map(e=>`<div class="elevator-detail"><strong>${esc2(e.elevatorNo)} · ${esc2(e.building)}</strong><div class="detail-grid"><span>Floors <b>${esc2(e.floorNo)}</b></span><span>Machine <b>${esc2(e.machineType)}</b></span><span>Door <b>${esc2(e.doorType)}</b></span><span>Status <b>${esc2(e.status)}</b></span><span>Capacity <b>${esc2(e.capacity)}</b></span><span>Speed <b>${esc2(e.speed)}</b></span><span>Installed <b>${esc2(e.installationYear)}</b></span></div></div>`).join(''):'<div class="empty-inline">No elevators registered.</div>'}</div></td><td><span class="badge ${o.status==='Active'?'green':'red'}">${esc2(o.status)}</span></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="small-btn" onclick="addElevator(${o.id})">+ Elevator</button><button class="small-btn" onclick="editOwner(${o.id})">Edit</button><button class="small-btn danger-btn" onclick="deleteOwner(${o.id})">Delete</button></div></td></tr>`}).join('')}
function renderTechnicians(){const el=document.getElementById('technicians');if(!el)return;const x=db();initCompanyFilter();el.innerHTML=x.technicians.filter(t=>!companyFilterVal()||t.companyId===companyFilterVal()).map(t=>`<tr><td><div class="person"><div class="avatar">${initials(t.name)}</div><div><b>${esc(t.name)}</b><small>${esc(t.email)}</small></div></div></td><td><span class="badge gold">${esc(companyName(t.companyId))}</span></td><td>${esc(t.phone)}</td><td><span class="badge gold">${esc(t.zone)}</span></td><td><span class="badge ${t.status==='Available'?'green':t.status==='Busy'?'gold':'red'}">${esc(t.status)}</span></td></tr>`).join('')}
function renderRequests(){const el=document.getElementById('adminRequests');if(!el)return;const x=db();initCompanyFilter();el.innerHTML=x.requests.filter(r=>!companyFilterVal()||reqCompanyId(x,r)===companyFilterVal()).map(r=>`<tr><td><b>${esc(r.id)}</b><small>${esc(r.issue)}</small></td><td><b>${esc(r.ownerName||'Unknown')}</b><small>${esc(r.ownerPhone||'No phone')}</small></td><td><span class="badge gold">${esc(companyName(reqCompanyId(x,r)))}</span></td><td><b>${esc(r.building)}</b><small>${esc(r.elevator)}</small></td><td>${esc(r.zone)}</td><td>${esc(r.problemDate||r.date||'—')}<small>${esc(r.time||'')}</small></td><td><span class="badge ${r.priority==='Emergency'?'red':r.priority==='High'?'gold':'green'}">${esc(r.priority)}</span></td><td>${esc(r.technician)}</td><td>${esc(r.status)}</td><td><button class="small-btn" onclick="assignRequest('${r.id}')">${r.technician==='Unassigned'?'Assign':'Reassign'}</button></td></tr>`).join('')}
function editOwner(id){const x=db(),o=x.owners.find(a=>a.id===id);if(!o)return;openModal('Edit owner',`<form onsubmit="submitOwnerEdit(event,${id})"><div class="form-grid"><label>Company<select id="ownerCompany" required>${companyOptions(o.companyId)}</select></label><label>Full name<input id="ownerName" required value="${esc(o.name)}"></label><label>Email<input id="ownerEmail" type="email" required value="${esc(o.email)}"></label><label>Phone<input id="ownerPhone" required value="${esc(o.phone)}"></label><label>Status<select id="ownerStatus"><option ${o.status==='Active'?'selected':''}>Active</option><option ${o.status==='Inactive'?'selected':''}>Inactive</option></select></label></div><button class="gold-btn" type="submit">Save owner</button></form>`)}
function submitOwnerEdit(e,id){e.preventDefault();const x=db(),o=x.owners.find(a=>a.id===id);o.name=ownerName.value;o.email=ownerEmail.value;o.phone=ownerPhone.value;o.status=ownerStatus.value;o.companyId=ownerCompany.value;syncPlatformUser(x,o,'Owner');saveDB(x);closeModal();renderOwners()}
function deleteOwner(id){if(!confirm('Delete this owner and all elevators linked to the owner?'))return;const x=db();const gone=x.owners.find(o=>o.id===id);if(gone)x.platformUsers=x.platformUsers.filter(u=>u.email!==gone.email.trim().toLowerCase());x.owners=x.owners.filter(o=>o.id!==id);x.elevators=(x.elevators||[]).filter(e=>e.ownerId!==id);saveDB(x);renderOwners()}
function addDailyRequest(){openModal('Create daily request',`<form onsubmit="submitDailyRequest(event)"><div class="form-grid"><label>Building<input id="reqBuilding" required placeholder="Building name"></label><label>Elevator No.<input id="reqElevator" required placeholder="L-01"></label><label>Zone<select id="reqZone">${['Nasr City','Maadi','New Cairo','Heliopolis'].map(z=>`<option>${z}</option>`).join('')}</select></label><label>Priority<select id="reqPriority"><option>Normal</option><option>High</option><option>Emergency</option></select></label><label>Issue<input id="reqIssue" required placeholder="Describe the problem"></label><label>Request date<input id="reqDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div><p class="hint">After creation, assign the request from the Requests page. Technician choices are filtered by zone.</p><button class="gold-btn" type="submit">Create request</button></form>`)}
function submitDailyRequest(e){e.preventDefault();const x=db();const owner=x.owners.find(o=>x.elevators.some(ev=>ev.ownerId===o.id&&ev.building===reqBuilding.value))||x.owners[0];x.requests.unshift({id:'#REQ-'+(1050+x.requests.length),ownerId:owner?.id,ownerName:owner?.name||'Unknown owner',ownerPhone:owner?.phone||'Not provided',building:reqBuilding.value,elevator:reqElevator.value,zone:reqZone.value,issue:reqIssue.value,priority:reqPriority.value,status:'Open',technician:'Unassigned',time:'Just now',date:reqDate.value,problemDate:reqDate.value});saveDB(x);closeModal();renderDailyRequests()}
function renderDailyRequests(){const el=document.getElementById('dailyRequests');if(!el)return;const x=db(),q=(document.getElementById('dailySearch')?.value||'').toLowerCase(),st=document.getElementById('dailyStatus')?.value||'',pr=document.getElementById('dailyPriority')?.value||'';initCompanyFilter();const rows=x.requests.filter(r=>(!companyFilterVal()||reqCompanyId(x,r)===companyFilterVal())&&(!q||[r.id,r.building,r.elevator,r.issue,r.zone,r.technician].join(' ').toLowerCase().includes(q))&&(!st||r.status===st)&&(!pr||r.priority===pr));el.innerHTML=rows.map(r=>`<tr><td><b>${esc(r.id)}</b><small>${esc(r.date||'Today')} · ${esc(r.time)}</small></td><td><span class="badge gold">${esc(companyName(reqCompanyId(x,r)))}</span></td><td><b>${esc(r.building)}</b><small>${esc(r.elevator)}</small></td><td>${esc(r.zone)}</td><td>${esc(r.issue)}</td><td><span class="badge ${r.priority==='Emergency'?'red':r.priority==='High'?'gold':'green'}">${esc(r.priority)}</span></td><td>${esc(r.technician)}</td><td>${esc(r.status)}</td><td><button class="small-btn" onclick="assignRequest('${esc(r.id)}')">${r.technician==='Unassigned'?'Assign':'Reassign'}</button></td></tr>`).join('')||`<tr><td colspan="9"><div class="empty-inline">No requests match the current filters.</div></td></tr>`}

function applicationStatusClass(status){return status==='Accepted'?'green':status==='Rejected'?'red':'gold'}
function renderTechnicianApplications(){
 const el=document.getElementById('technicianApplications'); if(!el)return;
 const x=db(), q=(document.getElementById('applicationSearch')?.value||'').toLowerCase(), st=document.getElementById('applicationStatus')?.value||'';
 const apps=x.technicianApplications||[], rows=apps.filter(a=>(!q||[a.id,a.name,a.email,a.phone,a.zone,a.experience,a.specializations].join(' ').toLowerCase().includes(q))&&(!st||a.status===st)&&(!companyFilterVal()||a.companyId===companyFilterVal()));
 initCompanyFilter();
 const count=(v)=>apps.filter(a=>a.status===v).length;
 document.getElementById('applicationPendingCount')?.replaceChildren(document.createTextNode(count('Pending')));
 document.getElementById('applicationAcceptedCount')?.replaceChildren(document.createTextNode(count('Accepted')));
 document.getElementById('applicationRejectedCount')?.replaceChildren(document.createTextNode(count('Rejected')));
 el.innerHTML=rows.map(a=>`<tr><td><div class="person"><div class="avatar">${initials(a.name)}</div><div><b>${esc(a.name)}</b><small>${esc(a.email)}</small></div></div></td><td><span class="badge gold">${esc(companyName(a.companyId))}</span></td><td>${esc(a.phone)}</td><td><span class="badge gold">${esc(a.zone)}</span></td><td>${esc(a.appliedDate)}</td><td><span class="badge ${applicationStatusClass(a.status)}">${esc(a.status)}</span></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="small-btn" onclick="viewTechnicianApplication('${esc(a.id)}')">View</button>${a.status==='Pending'?`<button class="small-btn accept-btn" onclick="acceptTechnicianApplication('${esc(a.id)}')">✓ Accept</button><button class="small-btn danger-btn" onclick="rejectTechnicianApplication('${esc(a.id)}')">✕ Reject</button>`:''}</div></td></tr>`).join('')||`<tr><td colspan="7"><div class="empty-inline">No technician applications match the current filters.</div></td></tr>`;
}
function viewTechnicianApplication(id){const x=db(),a=(x.technicianApplications||[]).find(v=>v.id===id);if(!a)return;openModal(`Technician application · ${esc(a.id)}`,`<div class="application-detail"><div class="application-profile"><div class="avatar large-avatar">${initials(a.name)}</div><div><h3>${esc(a.name)}</h3><p>${esc(a.experience)}</p></div><span class="badge ${applicationStatusClass(a.status)}">${esc(a.status)}</span></div><div class="detail-grid application-grid"><span>Email <b>${esc(a.email)}</b></span><span>Phone <b>${esc(a.phone)}</b></span><span>Zone <b>${esc(a.zone)}</b></span><span>Years experience <b>${esc(a.yearsExperience)}</b></span><span>Address <b>${esc(a.address)}</b></span><span>Applied date <b>${esc(a.appliedDate)}</b></span></div><div class="application-section"><span>Specializations</span><b>${esc(a.specializations)}</b></div><div class="application-section"><span>Applicant notes</span><b>${esc(a.notes||'No notes provided.')}</b></div>${a.status==='Pending'?`<div class="application-actions"><button class="gold-btn" onclick="acceptTechnicianApplication('${esc(a.id)}')">✓ Accept application</button><button class="small-btn danger-btn" onclick="rejectTechnicianApplication('${esc(a.id)}')">✕ Reject application</button></div>`:''}</div>`)}
function acceptTechnicianApplication(id){const x=db(),a=(x.technicianApplications||[]).find(v=>v.id===id);if(!a||a.status!=='Pending')return;if(!confirm(`Accept ${a.name} as a technician?`))return;const existing=x.technicians.find(t=>t.email===a.email||t.phone===a.phone);if(!existing){const nt={id:Date.now(),companyId:a.companyId,name:a.name,email:a.email,phone:a.phone,zone:a.zone,status:'Available'};x.technicians.push(nt);syncPlatformUser(x,nt,'Technician')}a.status='Accepted';a.reviewedDate='2026-09-10';a.reviewedBy='Admin';saveDB(x);closeModal();renderTechnicianApplications()}
function rejectTechnicianApplication(id){const x=db(),a=(x.technicianApplications||[]).find(v=>v.id===id);if(!a||a.status!=='Pending')return;openModal(`Reject application · ${esc(a.id)}`,`<form onsubmit="submitRejectApplication(event,'${esc(id)}')"><label>Rejection reason<textarea id="rejectReason" rows="4" placeholder="Optional reason for rejection"></textarea></label><div class="application-actions"><button type="button" class="small-btn" onclick="closeModal()">Cancel</button><button class="small-btn danger-btn" type="submit">✕ Reject application</button></div></form>`)}
function submitRejectApplication(e,id){e.preventDefault();const x=db(),a=(x.technicianApplications||[]).find(v=>v.id===id);if(!a)return;a.status='Rejected';a.rejectionReason=document.getElementById('rejectReason')?.value||'No reason provided.';a.reviewedDate='2026-09-10';a.reviewedBy='Admin';saveDB(x);closeModal();renderTechnicianApplications()}

const PLANS={Basic:{maxElevators:10,maxTechnicians:5},Pro:{maxElevators:50,maxTechnicians:20},Enterprise:{maxElevators:9999,maxTechnicians:9999}};
function addMonths(d,m){const x=new Date(d);x.setMonth(x.getMonth()+m);return x.toISOString().slice(0,10)}
function planLimit(v){return v>=9999?'Unlimited':v}
function renderCompanies(){
 const el=document.getElementById('companies'); if(!el)return;
 const x=db(), q=(document.getElementById('companySearch')?.value||'').toLowerCase();
 const rows=x.companies.filter(c=>!q||c.name.toLowerCase().includes(q));
 const set=(id,v)=>document.getElementById(id)?.replaceChildren(document.createTextNode(v));
 set('companyTotal',x.companies.length);set('companyActive',x.companies.filter(c=>c.active).length);set('companySuspended',x.companies.filter(c=>!c.active).length);set('userTotal',x.platformUsers.length);
 el.innerHTML=rows.map(c=>{const n=x.platformUsers.filter(u=>u.companyId===c.id).length;const adm=x.platformUsers.find(u=>u.companyId===c.id&&u.role==='Company Admin');const pending=adm&&adm.inviteCode;return `<tr><td><div class="person"><div class="avatar">${initials(c.name)}</div><div><b>${esc(c.name)}</b><small>Since ${esc(c.createdAt)}</small></div></div></td><td><span class="badge gold">${esc(c.plan||'—')}</span><small>${planLimit(c.maxElevators)} elevators · ${planLimit(c.maxTechnicians)} techs</small></td><td>${n} member(s)${pending?'<small>Invite pending</small>':''}</td><td>${esc(c.renewalDate||'—')}</td><td><span class="badge ${c.active?'green':'red'}">${c.active?'Active':'Suspended'}</span></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="small-btn" onclick="location.href='platform_users.html?company=${esc(c.id)}'">Users</button><button class="small-btn" onclick="editCompanyPlan('${esc(c.id)}')">Plan</button>${pending?`<button class="small-btn" onclick="showInvite('${esc(c.id)}')">Invite</button>`:''}<button class="small-btn ${c.active?'danger-btn':'accept-btn'}" onclick="toggleCompany('${esc(c.id)}')">${c.active?'Suspend':'Reactivate'}</button></div></td></tr>`}).join('')||`<tr><td colspan="6"><div class="empty-inline">No companies found.</div></td></tr>`;
}
function planOptions(sel){return Object.keys(PLANS).map(p=>`<option ${p===sel?'selected':''}>${p}</option>`).join('')}
function addCompany(){openModal('Add company',`<form onsubmit="submitCompany(event)"><div class="step-title">1. Company</div><div class="form-grid"><label>Company name<input id="coName" required placeholder="Company name"></label><label>Contact phone<input id="coPhone" placeholder="01xxxxxxxxx"></label></div><div class="step-title">2. Plan &amp; billing</div><div class="form-grid"><label>Plan<select id="coPlan" onchange="syncPlan()">${planOptions('Basic')}</select></label><label>Billing period<select id="coTerm"><option value="1">Monthly</option><option value="12" selected>Annual</option></select></label><label>Max elevators<input id="coElev" type="number" min="1" value="10"></label><label>Max technicians<input id="coTech" type="number" min="1" value="5"></label><label>Start date<input id="coStart" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div><div class="step-title">3. Company admin (first login)</div><div class="form-grid"><label>Admin name<input id="coAdminName" required placeholder="Full name"></label><label>Admin email<input id="coAdminEmail" type="email" required placeholder="admin@company.com"></label></div><p class="hint">An invite code is generated. Send it to the admin so they can set their own password and open the company dashboard and app.</p><button class="gold-btn" type="submit">Create company</button></form>`)}
function syncPlan(){const p=PLANS[coPlan.value];coElev.value=p.maxElevators;coTech.value=p.maxTechnicians}
function submitCompany(e){e.preventDefault();const x=db(),email=coAdminEmail.value.trim().toLowerCase();
 if(x.platformUsers.some(u=>u.email===email)){alert('A user with this email already exists.');return}
 const id='co-'+Date.now(),code=Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),start=coStart.value;
 x.companies.push({id,name:coName.value.trim(),phone:coPhone.value,createdAt:start,active:true,plan:coPlan.value,maxElevators:Number(coElev.value),maxTechnicians:Number(coTech.value),renewalDate:addMonths(start,Number(coTerm.value))});
 x.platformUsers.push({id:'u-'+Date.now(),companyId:id,name:coAdminName.value.trim(),email,role:'Company Admin',active:true,inviteCode:code});
 saveDB(x);closeModal();renderCompanies();showInvite(id)}
function showInvite(id){const x=db(),c=x.companies.find(a=>a.id===id),u=x.platformUsers.find(a=>a.companyId===id&&a.role==='Company Admin');if(!c||!u)return;
 const link=location.origin.startsWith('http')?location.origin+location.pathname.replace(/[^/]*$/,'')+'activate.html?code='+u.inviteCode:'activate.html?code='+u.inviteCode;
 openModal('Company created · '+esc(c.name),`<div class="assign-box"><div class="assign-request"><b>Send this to ${esc(u.name)} (${esc(u.email)})</b><span>Invite code: <b>${esc(u.inviteCode)}</b></span><span>Activation link: <b style="word-break:break-all">${esc(link)}</b></span></div><p class="hint">The admin opens the link, sets a password, and then signs in to the company dashboard and the mobile app with this email. The code works once.</p><button class="gold-btn" onclick="navigator.clipboard.writeText('${esc(link)}');this.textContent='Copied ✓'">Copy link</button></div>`)}
function editCompanyPlan(id){const c=db().companies.find(a=>a.id===id);if(!c)return;openModal('Plan · '+esc(c.name),`<form onsubmit="submitPlan(event,'${esc(id)}')"><div class="form-grid"><label>Plan<select id="coPlan" onchange="syncPlan()">${planOptions(c.plan)}</select></label><label>Max elevators<input id="coElev" type="number" min="1" value="${c.maxElevators}"></label><label>Max technicians<input id="coTech" type="number" min="1" value="${c.maxTechnicians}"></label><label>Renewal date<input id="coRenew" type="date" value="${esc(c.renewalDate||'')}"></label></div><button class="gold-btn" type="submit">Save plan</button></form>`)}
function submitPlan(e,id){e.preventDefault();const x=db(),c=x.companies.find(a=>a.id===id);c.plan=coPlan.value;c.maxElevators=Number(coElev.value);c.maxTechnicians=Number(coTech.value);c.renewalDate=coRenew.value;saveDB(x);closeModal();renderCompanies()}
function toggleCompany(id){const x=db(),c=x.companies.find(a=>a.id===id);if(!c)return;if(c.active&&!confirm(`Suspend ${c.name}? All its owners and technicians will be blocked from signing in.`))return;c.active=!c.active;saveDB(x);renderCompanies()}
function renderPlatformUsers(){
 const el=document.getElementById('platformUsers'); if(!el)return;
 const x=db(), cid=new URLSearchParams(location.search).get('company')||'', q=(document.getElementById('userSearch')?.value||'').toLowerCase();
 const co=x.companies.find(c=>c.id===cid);
 const title=document.getElementById('usersTitle'); if(title)title.textContent=co?`Users · ${co.name}`:'All users';
 const rows=x.platformUsers.filter(u=>(!cid||u.companyId===cid)&&(!q||[u.name,u.email,u.role].join(' ').toLowerCase().includes(q)));
 el.innerHTML=rows.map(u=>{const c=x.companies.find(c=>c.id===u.companyId);return `<tr><td><div class="person"><div class="avatar">${initials(u.name)}</div><div><b>${esc(u.name)}</b><small>${esc(u.email)}</small></div></div></td><td>${esc(u.role)}</td><td>${esc(c?c.name:'—')}</td><td><span class="badge ${u.active?'green':'red'}">${u.active?'Active':'Suspended'}</span></td><td><button class="small-btn ${u.active?'danger-btn':'accept-btn'}" onclick="toggleUser('${esc(u.id)}')">${u.active?'Suspend':'Reactivate'}</button></td></tr>`}).join('')||`<tr><td colspan="5"><div class="empty-inline">No users found.</div></td></tr>`;
}
function toggleUser(id){const x=db(),u=x.platformUsers.find(a=>a.id===id);if(!u)return;u.active=!u.active;saveDB(x);renderPlatformUsers()}

function activateAccount(e){e.preventDefault();const x=db(),code=document.getElementById('actCode').value.trim().toUpperCase(),u=x.platformUsers.find(a=>a.inviteCode===code);
 const err=document.getElementById('actErr');if(!u){err.textContent='Invalid or already used invite code.';return}
 const p1=document.getElementById('actPw').value;if(p1.length<6){err.textContent='Password must be at least 6 characters.';return}
 // DEMO ONLY: a real backend must hash the password server-side.
 u.password=p1;delete u.inviteCode;saveDB(x);document.getElementById('actBody').innerHTML='<h1>Account activated</h1><p>'+esc(u.email)+' can now sign in to the company dashboard and the app.</p>'}

function money(v){return 'EGP '+Number(v).toLocaleString('en-US')}
const DEAL_STATUSES=['Awarded','In progress','Completed','Cancelled'];
function dealBadge(st){return st==='Completed'?'green':st==='Cancelled'?'red':'gold'}
function renderInstallations(){
 const el=document.getElementById('deals'); if(!el)return;
 const x=db(),live=x.installationDeals.filter(d=>d.winner&&d.status!=='Cancelled');
 const set=(id,v)=>document.getElementById(id)?.replaceChildren(document.createTextNode(v));
 set('dealTotal',x.installationDeals.length);set('dealAwarded',live.length);
 set('dealVolume',money(live.reduce((a,d)=>a+d.price,0)));
 set('dealEarnings',money(live.reduce((a,d)=>a+d.price*d.commissionPercent/100,0)));
 const inp=document.getElementById('commissionInput');if(inp&&document.activeElement!==inp)inp.value=x.commissionPercent;
 el.innerHTML=x.installationDeals.map(d=>`<tr><td><b>${esc(d.id)}</b><small>${esc(d.date)}</small></td><td>${esc(d.building)}<small>${esc(d.area)}</small></td><td>${esc(d.requester)}</td><td>${esc(d.winner||'—')}<small>${d.offers.length} offer(s) · shared with ${(d.sharedWith||[]).length}</small></td><td>${d.price?money(d.price):'—'}</td><td>${d.winner?esc(d.commissionPercent)+'% · <b>'+money(d.price*d.commissionPercent/100)+'</b><small>'+(d.commissionPaid?'Paid':'Unpaid')+'</small>':'—'}</td><td><span class="badge ${dealBadge(d.status)}">${esc(d.status)}</span>${d.startDate?'<small>'+esc(d.startDate)+' → '+esc(d.endDate||'?')+'</small>':''}</td><td><button class="small-btn" onclick="viewDeal('${esc(d.id)}')">Details</button></td></tr>`).join('')||`<tr><td colspan="8"><div class="empty-inline">No installation requests yet.</div></td></tr>`;
}
function today(){return new Date().toISOString().slice(0,10)}
function recommendedOffer(d){
 const o=d.offers||[];if(!o.length)return null;
 const minP=Math.min(...o.map(a=>a.price)),minD=Math.min(...o.map(a=>a.days||1));
 // 70% price, 30% duration: the lowest weighted score is the optimal offer
 return o.slice().sort((a,b)=>(0.7*a.price/minP+0.3*(a.days||1)/minD)-(0.7*b.price/minP+0.3*(b.days||1)/minD))[0];
}
function companyIdByName(x,name){const c=x.companies.find(c=>c.name===name);return c?c.id:''}
function viewDeal(id){
 const x=db(),d=x.installationDeals.find(a=>a.id===id);if(!d)return;
 const offers=d.offers.slice().sort((a,b)=>a.price-b.price),rec=recommendedOffer(d);
 const shared=(d.sharedWith||[]).length;
 const offersTbl=offers.length?`<div class="table-wrap"><table style="min-width:0"><thead><tr><th>Company</th><th>Price</th><th>Days</th><th></th></tr></thead><tbody>${offers.map(o=>`<tr><td><b>${esc(o.company)}</b>${rec&&o.company===rec.company?' <span class="badge gold">Recommended</span>':''}${o.note?'<small>'+esc(o.note)+'</small>':''}</td><td>${money(o.price)}</td><td>${esc(o.days)}</td><td>${d.status==='Open'?`<button class="small-btn accept-btn" onclick="awardDeal('${esc(d.id)}','${esc(o.company)}')">Award</button>`:o.company===d.winner?'<span class="badge green">Winner</span>':''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-inline">No offers yet. Companies that receive this request can bid from their app.</div>';
 const recBar=d.status==='Open'&&rec?`<div class="application-actions"><button class="gold-btn" onclick="awardDeal('${esc(d.id)}','${esc(rec.company)}')">★ Award recommended offer</button><span class="hint">Best balance of price (70%) and installation time (30%): ${esc(rec.company)} · ${money(rec.price)} · ${esc(rec.days)} days.</span></div>`:'';
 const addOffer=d.status==='Open'?`<button class="small-btn" onclick="addManualOffer('${esc(d.id)}')">+ Add offer manually</button>`:'';
 const techs=d.winner?x.technicians.filter(t=>t.companyId===companyIdByName(x,d.winner)):[];
 const controls=d.winner?`<div class="step-title">Installation schedule</div><div class="form-grid"><label>Start date<input id="dealStart" type="date" value="${esc(d.startDate||'')}"></label><label>Duration (days)<input id="dealDays" type="number" min="1" value="${esc(d.days||'')}"></label><label>Installation lead<select id="dealLead"><option value="">Not assigned</option>${techs.map(t=>`<option ${t.name===d.leadTech?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Planned finish<input id="dealEnd" type="date" value="${esc(d.endDate||'')}" disabled></label></div><div class="step-title">Control the installing company</div><div class="form-grid"><label>Installation status<select id="dealStatus">${DEAL_STATUSES.map(s=>`<option ${s===d.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Commission<select id="dealPaid"><option value="0" ${d.commissionPaid?'':'selected'}>Unpaid</option><option value="1" ${d.commissionPaid?'selected':''}>Paid</option></select></label><label>Reassign to another bidder<select id="dealReassign"><option value="">Keep ${esc(d.winner)}</option>${offers.filter(o=>o.company!==d.winner).map(o=>`<option>${esc(o.company)}</option>`).join('')}</select></label></div><label>Admin note<textarea id="dealNote" rows="3" placeholder="Internal note about this installation">${esc(d.adminNote||'')}</textarea></label><div class="application-actions"><button class="gold-btn" onclick="saveDeal('${esc(d.id)}')">Save changes</button><button class="small-btn danger-btn" onclick="revokeDeal('${esc(d.id)}')">Revoke award &amp; reopen</button></div>`:'';
 openModal('Installation · '+esc(d.id),`<div class="application-detail"><div class="detail-grid application-grid"><span>Requested by <b>${esc(d.requester)}</b></span><span>Contact <b>${esc(d.requesterName)}</b></span><span>Building <b>${esc(d.building)}</b></span><span>Area <b>${esc(d.area)}</b></span><span>Address <b>${esc(d.address)}</b></span><span>Floors <b>${esc(d.floors)}</b></span><span>Elevator type <b>${esc(d.elevatorType)}</b></span><span>Capacity <b>${esc(d.capacity)}</b></span><span>Request date <b>${esc(d.date)}</b></span><span>Status <b>${esc(d.status)}</b></span><span>Shared with <b>${shared} compan${shared===1?'y':'ies'}</b></span></div><div class="application-section"><span>Notes</span><b>${esc(d.notes||'No notes provided.')}</b></div><div class="step-title">Offers</div>${offersTbl}${addOffer}${recBar}${controls}</div>`);
 const upd=()=>{const st=document.getElementById('dealStart'),dy=document.getElementById('dealDays'),en=document.getElementById('dealEnd');if(st&&dy&&en){en.value=st.value&&Number(dy.value)>0?addDays(st.value,Number(dy.value)):''}};
 const st=document.getElementById('dealStart'),dy=document.getElementById('dealDays');if(st){st.oninput=upd;dy.oninput=upd;upd()}
}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function addInstallRequest(){
 const x=db();
 openModal('New installation request',`<form onsubmit="submitInstallRequest(event)"><div class="form-grid"><label>Requested by (company)<select id="irCompany">${companyOptions()}</select></label><label>Contact name<input id="irContact" required placeholder="Owner name"></label><label>Building name<input id="irBuilding" required placeholder="Building name"></label><label>Area / zone<input id="irArea" required placeholder="Nasr City"></label><label>Address<input id="irAddress" required placeholder="Street, district"></label><label>Floors<input id="irFloors" type="number" min="1" required placeholder="18"></label><label>Elevator type<select id="irType"><option>Gearless</option><option>Geared</option><option>Hydraulic</option><option>MRL</option></select></label><label>Capacity<input id="irCap" required placeholder="1000 kg / 13 persons"></label></div><label>Notes<textarea id="irNotes" rows="3" placeholder="Anything the companies should know"></textarea></label><p class="hint">The request is shared with every active company. Their offers appear here so you can pick the best one.</p><button class="gold-btn" type="submit">Share with all companies</button></form>`);
}
function submitInstallRequest(e){
 e.preventDefault();const x=db(),co=x.companies.find(c=>c.id===irCompany.value);
 const n=x.installationDeals.length+1;let id='INST-'+n;while(x.installationDeals.some(d=>d.id===id))id='INST-'+(++n);
 x.installationDeals.unshift({id,date:today(),requester:co?co.name:'—',requesterName:irContact.value,building:irBuilding.value,area:irArea.value,address:irAddress.value,floors:Number(irFloors.value),elevatorType:irType.value,capacity:irCap.value,notes:irNotes.value,status:'Open',winner:'',price:0,days:0,commissionPercent:0,commissionPaid:false,adminNote:'',offers:[],sharedWith:x.companies.filter(c=>c.active&&(!co||c.id!==co.id)).map(c=>c.id)});
 saveDB(x);renderInstallations();viewDeal(id)}
function addManualOffer(id){
 const x=db(),d=x.installationDeals.find(a=>a.id===id);if(!d)return;
 const taken=d.offers.map(o=>o.company),cands=x.companies.filter(c=>c.active&&c.name!==d.requester&&!taken.includes(c.name));
 if(!cands.length){alert('Every eligible company has already made an offer.');return}
 openModal('Add offer · '+esc(id),`<form onsubmit="submitManualOffer(event,'${esc(id)}')"><div class="form-grid"><label>Company<select id="moCompany">${cands.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select></label><label>Price (EGP)<input id="moPrice" type="number" min="1" required></label><label>Installation days<input id="moDays" type="number" min="1" required></label><label>Note<input id="moNote" placeholder="Optional"></label></div><button class="gold-btn" type="submit">Add offer</button></form>`)}
function submitManualOffer(e,id){
 e.preventDefault();const x=db(),d=x.installationDeals.find(a=>a.id===id);
 d.offers.push({company:moCompany.value,price:Number(moPrice.value),days:Number(moDays.value),note:moNote.value});saveDB(x);renderInstallations();viewDeal(id)}
function awardDeal(id,company){
 const x=db(),d=x.installationDeals.find(a=>a.id===id),o=d&&d.offers.find(a=>a.company===company);if(!o)return;
 if(!confirm(`Award ${id} to ${company} for ${money(o.price)}?`))return;
 d.winner=company;d.price=o.price;d.days=o.days;d.commissionPercent=x.commissionPercent;d.commissionPaid=false;d.status='Awarded';saveDB(x);renderInstallations();viewDeal(id)}
function saveDeal(id){
 const x=db(),d=x.installationDeals.find(a=>a.id===id);if(!d)return;
 const re=document.getElementById('dealReassign').value;
 if(re){const o=d.offers.find(a=>a.company===re);if(o){if(!confirm(`Reassign ${id} from ${d.winner} to ${re}?`))return;d.winner=re;d.price=o.price;d.days=o.days;d.leadTech=''}}
 d.status=document.getElementById('dealStatus').value;
 d.commissionPaid=document.getElementById('dealPaid').value==='1';
 d.adminNote=document.getElementById('dealNote').value;
 if(!re){d.startDate=document.getElementById('dealStart').value;d.days=Number(document.getElementById('dealDays').value)||d.days;d.endDate=d.startDate?addDays(d.startDate,d.days):'';d.leadTech=document.getElementById('dealLead').value}
 saveDB(x);closeModal();renderInstallations()}
function revokeDeal(id){
 if(!confirm('Revoke the award and reopen this request for new decisions?'))return;
 const x=db(),d=x.installationDeals.find(a=>a.id===id);if(!d)return;
 d.winner='';d.price=0;d.days=0;d.commissionPercent=0;d.commissionPaid=false;d.startDate='';d.endDate='';d.leadTech='';d.status='Open';saveDB(x);closeModal();renderInstallations()}
function saveCommission(){const v=Number(document.getElementById('commissionInput').value);if(!(v>=0&&v<=100)){alert('Enter a percentage between 0 and 100.');return}const x=db();x.commissionPercent=v;saveDB(x);renderInstallations();alert('Commission set to '+v+'%. It applies to offers accepted from now on; closed deals keep their rate.')}

function renderElevators(){
 const el=document.getElementById('elevatorsBody'); if(!el)return;
 initCompanyFilter();
 const x=db(),cf=companyFilterVal();
 const rows=x.elevators.map(e=>({e,o:x.owners.find(o=>o.id===e.ownerId)})).filter(r=>!cf||(r.o&&r.o.companyId===cf));
 document.getElementById('elevatorCount')?.replaceChildren(document.createTextNode(rows.length+' units'));
 el.innerHTML=rows.map(({e,o})=>`<tr><td><b>${esc(e.elevatorNo)}</b></td><td>${esc(o?o.name:'—')}</td><td><span class="badge gold">${esc(o?companyName(o.companyId):'—')}</span></td><td>${esc(e.building)}</td><td>${esc(e.floorNo)}</td><td>${esc(e.machineType)}</td><td>${esc(e.doorType)}</td><td>${esc(e.capacity)}</td><td>${esc(e.speed)}</td><td>${esc(e.installationYear)}</td><td><span class="badge ${e.status==='Operational'?'green':e.status==='Maintenance'?'gold':'red'}">${esc(e.status)}</span></td></tr>`).join('')||`<tr><td colspan="11"><div class="empty-inline">No elevators registered.</div></td></tr>`;
}
